### ISSUE TITLE
publisher failure

### ISSUE THREAD

**Issue by 4383** [nathan-hoche/MonaLisa#5]
Hi Nathan,

I see that your pypi publisher still fail, had you setup a pypi "pending publisher" like explained [here](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/)?

**Comment by 4383** [comment]
Apparently you are now facing an invalid token failure https://github.com/nathan-hoche/MonaLisa/actions/runs/12020239336

**Comment by nathan-hoche** [comment]
Hi,

Yes I setup the pypi as explained in the link. I think I need to modify the main.yml to publish with the new pypi name, I did not take the time to test that, I will try to fix it now!

**Comment by 4383** [comment]
That's weird.

Normally your github actions are agnostic to project config. I always reuse the same setup for actions when I start a new project and I never needed to update name or project data.

By example today I created a new project (https://github.com/4383/defected), and I simply copied the same github actions than yours. I was able to publish on pypi directly from the beginning of my new project (https://pypi.org/project/defected/)

**Comment by 4383** [comment]
Oh wait!

https://pypi.org/project/monailisa/

Kudos!

So... is the name was again the problem?

**Comment by nathan-hoche** [comment]
Fixed: The problem was due to two main mistakes:
1. The api token for the pypi project wasn't publish on github settings blocking the request
2. Then I needed to rename all "monalisa" to "monailisa" (such as in the pyproject.toml) to use the new name

**Comment by 4383** [comment]
I got it. Thanks for details.

**Comment by nathan-hoche** [comment]
Thanks for your help!
